image: node:20

stages:
  - build
  - deploy

cache:
  key:
    files:
      - project/package-lock.json
  paths:
    - project/node_modules/

build:
  stage: build
  script:
    - cd project
    - npm ci
    - npm run build
  artifacts:
    paths:
      - project/dist

pages:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - mkdir public
    - cp -r project/dist/. public/
  pages:
    publish: public
  rules:
    - if: '$CI_COMMIT_BRANCH == "reactDeploy"'