image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - project/node_modules/

build-job:
  stage: build
  script:
    - cd project
    - npm install
    - npm run build
    - mv build ../public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - reactDeploy
